// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osapi-io/nats-server/pkg/server (interfaces: NATSServerInstance)
//
// Generated by this command:
//
//	mockgen -destination=./nats_server_instance.gen.go -package=mocks github.com/osapi-io/nats-server/pkg/server NATSServerInstance
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	server "github.com/nats-io/nats-server/v2/server"
	gomock "go.uber.org/mock/gomock"
)

// MockNATSServerInstance is a mock of NATSServerInstance interface.
type MockNATSServerInstance struct {
	ctrl     *gomock.Controller
	recorder *MockNATSServerInstanceMockRecorder
	isgomock struct{}
}

// MockNATSServerInstanceMockRecorder is the mock recorder for MockNATSServerInstance.
type MockNATSServerInstanceMockRecorder struct {
	mock *MockNATSServerInstance
}

// NewMockNATSServerInstance creates a new mock instance.
func NewMockNATSServerInstance(ctrl *gomock.Controller) *MockNATSServerInstance {
	mock := &MockNATSServerInstance{ctrl: ctrl}
	mock.recorder = &MockNATSServerInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSServerInstance) EXPECT() *MockNATSServerInstanceMockRecorder {
	return m.recorder
}

// ReadyForConnections mocks base method.
func (m *MockNATSServerInstance) ReadyForConnections(timeout time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyForConnections", timeout)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReadyForConnections indicates an expected call of ReadyForConnections.
func (mr *MockNATSServerInstanceMockRecorder) ReadyForConnections(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyForConnections", reflect.TypeOf((*MockNATSServerInstance)(nil).ReadyForConnections), timeout)
}

// SetLogger mocks base method.
func (m *MockNATSServerInstance) SetLogger(logger server.Logger, debug, trace bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", logger, debug, trace)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockNATSServerInstanceMockRecorder) SetLogger(logger, debug, trace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockNATSServerInstance)(nil).SetLogger), logger, debug, trace)
}

// Shutdown mocks base method.
func (m *MockNATSServerInstance) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockNATSServerInstanceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockNATSServerInstance)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockNATSServerInstance) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockNATSServerInstanceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNATSServerInstance)(nil).Start))
}
